### ISSUE TITLE
Ability to apply classes to the parent of the elements

### ISSUE THREAD

**Issue by sebastianbarfurth** [verlok/lazyload#115]
Having the ability to put the classes higher up in the element tree would make CSS work on the images a lot easier, since CSS can only select down the hierarchy and not up. This way the parent container could be animated (or whatever else) based on the the status of the image.

A simple example would be an overlay over the images. The markup for that would look something like this:

```html
<div>
  <div class="overlay">Overlay text here!</div>
  <img data-original="/img/front-1.jpeg" alt="..." class="loaded">
</div>
``` 

Since we need to define all of these in HTML we have no way to hide the parent and the overlay until the image is actually loaded, this would generate odd visual effects. Essentially we have overlays without images.

Of course this could be done with JavaScript, but simply having the classes apply to a parent would make this a lot easier. This is a thought I had while developing just now.

**Comment by verlok** [comment]
Hi @sebastianbarfuth and thanks for your input. 

Have you checked the callbacks that you can pass in as options to LazyLoad?

You can use the `callback_loaded`, which is called exactly when the `loaded` class is set by LazyLoad, to set the class to whatever element you want up in the DOM tree. 

There's actually no difference, in terms of performance, between you making it in your JavaScript, and my script doing it. Except that I cannot do it in my script because I simply don't know what there's up in the DOM tree, since it could be executed on any image (a banner, a product, a menu item...)

**Comment by sebastianbarfurth** [comment]
I'll see about it, it was just a thought I had while working with the script.
