### ISSUE TITLE
LazyLoad hidden images

### ISSUE THREAD

**Issue by warudin** [verlok/lazyload#129]
I'd like to know if it's possible to force lazyLoad to load images that aren't visible at a certain moment. 

More specifically, I want to use this for a slider which uses background images. I'd like to load the backgrounds for the next two images when the slider is initialized and when the position is changed.

**Comment by verlok** [comment]
Well, I never tested it on a slider because version until 8 worked listening to the container's scroll event, which is not triggered by a slider. But I guess that this could work from version 9 up. 

Just set the `threshold` option to the amount of pixels beyond the slider that you want to start loading the images at. 

In your case, if the slider is horizontal and the images are 300px wide, set the threshold option to `301` and you will have the next images loaded. 

Let me know if it worked :)

**Comment by verlok** [comment]
I'm considering this closed. If it's not, feel free to open it again.
