### ISSUE TITLE
IntersectionObserver polyfill and performance

### ISSUE THREAD

**Issue by Tabrisrp** [verlok/lazyload#139]
Hi,

W3C is providing an official IntersectionObserver polyfill here: https://github.com/w3c/IntersectionObserver/tree/master/polyfill

Would it make sense to use it with version 10 of lazyload, compared to using version 8 without polyfill, in term of performance? 

Is there any special configuration to be made for the polyfill to work with lazyload or will it work out of the box?

**Comment by verlok** [comment]
Bonjour Rémy,
thanks for asking and congratulations for your website, awesome web typography and content. 

Actually you’re not the first asking this, I got the same question on Twitter. Here’s what I think:

- In terms of loading performance, since the polyfill script is quite heavy compared to LazyLoad 8, downloading LazyLoad 10 + the polyfill would be worse, so be sure to load the polyfill conditionally only when it’s really needed (currently Safari and IE).
- In terms of CPU performance you would have an improvement using LazyLoad 10 where IntersectionObserver is supported since it is native and faster, but I didn’t measure CPU performance of LazyLoad 10 + the polyfill. 

If you need the IO polyfill to make other scripts work too, I’d go for the polyfill, loading it conditionally only where it’s needed, and LazyLoad 10. 

If you don’t need the IO polyfill for scripts other than LazyLoad, and you have the ability to selectively load scripts depending on the browser, you could load LazyLoad 10 or LazyLoad 8 conditionally, depending on browser support of IO. 


The simplest and performant way to load LazyLoad is of course to only load version 8, which works everywhere. It’s not that fast and modern as LazyLoad 10, but it’s still fast and it does the job exactly as it did it for the latest 5 years :)

If you need more information, please ask. 

Cheers!
Andrea

**Comment by Tabrisrp** [comment]
Thank you for your answer and advices, makes choosing easier with your input! 👍

**Comment by verlok** [comment]
I’m glad you appreciated it. 
Cheers!
