### ISSUE TITLE
Class loading not being removed for background images

### ISSUE THREAD

**Issue by xpander001** [verlok/lazyload#151]
I am trying to add a fade in effect for lazy loaded background images. However, looks like the loaded class is never added to the element.

Does that class work with background images? I see you have callbacks for load events on img tags, but cannot spot in the source code if you fire events for background image events. I think that according to the setSources method, the code relies on setting the background image if the element is no iframe or img, and then it does not fire any event. Is it ok?

Thanks!

**Comment by verlok** [comment]
Hi @xpander001,
thank you for writing this.

The reason why my script doesn't do anything when a background image is loaded is because there is no way to know when a background image is loaded in Javascript. Browsers simply won't fire any event or call any callback when a background image is loaded, and they don't because background images are meant for decorative purposes only, they could be removed from the page and nobody would care.

And this closes the issue (there are other similar issues already closed, I guess).

But from the way you are putting it, it looks like the images you're loading lazily are not just decorative images, but they are meaningful content instead. If they are meaningful content, you should really think again and use the `img` tag instead. If you used it, you could:

- know when the images are loaded (and having the "loading" class removed by the script)
- benefit from SEO since crawlers would index your images and your `alt` text content
- help visually impaired users read your images through assistive technology 

and more, like make your images responsive and so on!

**Comment by xpander001** [comment]
Hi @verlok .

Thank you for your response. My reason to use background images instead of img tags if because I need to maintain the aspect ratio with cover in browsers as old as IE9 (So cannot use object fit).

I added a small workaround (terribly dirty, I know) is your library, that goes like this:

```
if (elementSrc) {
  var img = new Image();
  img.onload = function() {
    element.style.backgroundImage = 'url("' + elementSrc + '")';
    addClass(element, settings.class_loaded);
  }
  img.src = elementSrc;
}
```

But at least for the moment is doing the job. What are the main drawbacks you see to this approach?

And thank you for your response again!

**Comment by verlok** [comment]
Hi and thank you for your reply. 

The only drawback I see is a performance one. Users on slow connections, like on mobile or slow networks, will only see the image once loaded instead of while loading. 

But hey, IE9, really? Are you sure that you have more than 0.5% of users coming to your website using that browser/version? Have you checked on Google Analytics?

**Comment by xpander001** [comment]
@verlok requirements... :)

**Comment by verlok** [comment]
Hey @xpander001,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Have a nice day.
