### ISSUE TITLE
Not using requestanimationframe ?

### ISSUE THREAD

**Issue by alvarotrigo** [verlok/lazyload#161]
This is just a question out of curiosity. 

I noticed you seem to be using a `setTimeout` function instead of `requestanimationframe` to loop and check the scroll value.

Is there a reason behind it? I would though [requestAnimationFrame is better in terms of reducing unnecessary operations](https://stackoverflow.com/questions/38709923/why-is-requestanimationframe-better-than-setinterval-or-settimeout) ?

**Comment by verlok** [comment]
The `setTimeout` function is used only to throttle the calls to the scroll / resize handler function. It's used only on version 8 since the `IntersectionObserver` doesn't need to.

**Comment by alvarotrigo** [comment]
Wouldn't it be a performance improvement to use `requestAnimationFrame` in version 8 at the moment? 

Browsers like IE 11 or Safari [don't seem to support `Intersectionobserver`](https://caniuse.com/#feat=intersectionobserver) but [they do support `requestanimationframe`](https://caniuse.com/#feat=requestanimationframe). And for older browsers [there's a polyfill](https://gist.github.com/paulirish/1579671).

**Comment by verlok** [comment]
Yes it would, I didn't do it until now because I didn't focus on improving performance in version 8.
I just looked up whether or not it's possible to use requestAnimationFrame to debounce scroll handlers.
It seems that [it's possible](https://gomakethings.com/debouncing-events-with-requestanimationframe-for-better-performance/).

**Comment by verlok** [comment]
Hi @alvarotrigo,

I've read [this article](https://css-tricks.com/debouncing-throttling-explained-examples/) thoroughly, and not I've got an answer to your question.

The answer is no, `requestAnimationFrame` wouldn't be a performance improvement. 

The reason is that the `throttle` function used internally by LazyLoad makes sure that the `scroll` event is executed not faster than every 150 ms (by default, but this is an option). Using `requestAnimationFrame` would execute it every 16 ms, and this is unnecessary.

The usage of `requestAnimationFrame` is highly recommended in scripts generating animations, like drawing on the screen, changing the layout of DOM elements, to guarantee the render at 60 fps. I think that this is not the case of LazyLoad.

Let me know if you had something else in mind, otherwise I'll close this issue.

Merry Christmas!

**Comment by alvarotrigo** [comment]
Yeap, totally clear now :) Make sense.
