### ISSUE TITLE
Why is isBelowViewport function using the container height as the fold?

### ISSUE THREAD

**Issue by ikanedo** [verlok/lazyload#162]
Hi,

In 8.5.2 version, we have the following **isBelowViewport** function

```js
    var isBelowViewport = function isBelowViewport(element, container, threshold) {
        var fold = container === window ? window.innerHeight + window.pageYOffset : getTopOffset(container) + container.offsetHeight;
        return fold <= getTopOffset(element) - threshold;
    };
```

I was just wondering, why does the function use the container bottom offset as the fold if the container is not the window object? This would mean that if the container is bigger than the viewport then all of the images within the container are loaded in the initial page load. Is this the expected behaviour?

See sample issue here
https://jsfiddle.net/zvm84njL/1/

**Comment by verlok** [comment]
Hi @ikanedo,
you’re right. Could you do a pull request to fix this?
Thanks

**Comment by verlok** [comment]
Verified the bug in the jsfiddle. @ikanedo would you be able to fix this with a pull request?

**Comment by verlok** [comment]
Hi again @ikanedo.
I transported your example to a [Pen](https://codepen.io/verlok/pen/VyVLXv) on Codepen and applied some CSS fixes to it.
The scrolling container needed to have a height, and the lazy images needed to have a `min-height` at least, in order to avoid being loaded all at once. 
Once fixed those issues, the script works as expected. Am I missing something?
