### ISSUE TITLE
Load images one after another

### ISSUE THREAD

**Issue by liborvanek** [verlok/lazyload#164]
**Are you reporting a bug or requesting a feature?**
A feature

Would it be possible to have an option to force lazyload to start downloading next image after the previous one is finished?

In my case, I have two images that trigger lazyload at the same time. They also appear roughly at the same time because they're downloaded in parallel. On fast connection, that's fine. But on slower  it increases time to First Meaningful Paint. In this case serial loading would improve the user experience.

BTW thanks for the great work.

**Comment by verlok** [comment]
Hi @liborvanek,
that's a good question.

Let me think... so you want to block parallel loading of all the images in order to reduce the TTFMP (time to first meaningful paint), giving control to Javascript instead of the browser to download the images in series instead of in parallel.

I can't see how this could perform better, since parallel loading fills the gaps of network round trips that would occur while downloading one single image. Are you sure of what you're asking? Have you tried and measured that?

I don't think I will develop this feature inside the LazyLoad, since it's a very singular request and it would add code which is unused by most... but maybe we can think of a workaround which uses the callbacks provided by LazyLoad to do so. 

Here's what I suggest: 

1. you demonstrate that serial loading is better than parallel loading in order to reduce TTFMP
2. we work together to a workaround which uses LazyLoad's callbacks to achieve that.

What do you think?

**Comment by liborvanek** [comment]
Hi verlok,
thanks for a quick reply!
My idea actually came came from performance measurements, but I didn't give it that much time. It's based on a simple assumption, that downloading one image would be significantely faster than downloading two at the same time.

I'll try to measure more and build proof of case using current callbacks.

**Comment by liborvanek** [comment]
So I made a quick demo:
## Parallel mode
https://5a552a19a6188f73127302a6--mlnjrs.netlify.com

## Serial mode
https://5a5529a84c4b935a77cf0779--mlnjrs.netlify.com

I ran couple of tests using Performance tab in Chrome with network throttled to "Fast 3G".

After averaging the results, it took approximately **3,6 seconds** from First Paint to first `callback_load` that triggers first animation in Parallel mode. In Serial mode, it took about **2,6 seconds**. That looks like reasonable gain to me.
The site is depolyed on Netlify with HTTP/2 available.

Serial mode callback:
```
  const lazy1 = new LazyLoad({
  elements_selector: '.load-first',
  threshold: 50,
  callback_enter: (el) => {
    console.log(Date.now())
  },
  callback_load: (el) => {
    GsapTimeline1.play()
    const lazy2 = new LazyLoad({
      elements_selector: '.load-second',
      threshold: 50,
      callback_enter: (el) => {
        console.log(Date.now())
      },
      callback_load: (el) => {
        GsapTimeline2.play()
      }
    })
  }
})
```
Any ideas about this?

**Comment by verlok** [comment]
Hi @liborvanek,

I'm still not convinced that serial mode can be faster than parallel, because if you go serial there will be a network idle time between one image load and the next image start loading, whereas parrallel loading minimizes that.

You would need to do a demo A) in which 50 images load in parallel, and another B) in which they load in series. I'm convinced that A) would be faster.

Anyway the best pratice on pages is to eagerly load the first N images (N being the number of images "above the fold"), then start lazily loading from the N+1 on.

[See this repo of best practices](https://github.com/verlok/productListingPageBestPractices) to read more and see the code.
