### ISSUE TITLE
Threshold property on scrolling window doesn't work on both vertically and horizontally.

### ISSUE THREAD

**Issue by weplan9** [verlok/lazyload#172]
Are you reporting a bug or requesting a feature?
BUG

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening?
Threshold property is not working when images are in scroll window.

If i use the `elements_selector` with callback function - Threshold property starts working horizontally and stops working vertically.

* What is the expected behaviour?
Threshold property should work vertically and horizontally.

* Which version of LazyLoad are you using?
10.4.2

* In which browser(s) and browser version(s) are you experiencing the problem?
Chrome

* Could you provide the HTML, CSS and JS code you use for your images?
https://codepen.io/anon/pen/RxzVEy

* What are the steps to reproduce the problem?
I have provided the codepen. However Threshold property don't work in codepen window as it is itself a scrolling window.

But vertically threshold does work.

Replace the JS with the fowlloing:

`var lazyLoadInstances = [];
// The "lazyLazy" instance of lazyload is used (kinda improperly) 
// to check when the .horzContainer divs enter the viewport
var lazyLazy = new LazyLoad({
    elements_selector: ".scrollScreenShots",
    // When the .horzContainer div enters the viewport...
    callback_set: function(el) {
        // ...instantiate a new LazyLoad on it
        var oneLL = new LazyLoad({
            container: el
        });
        // Optionally push it in the lazyLoadInstances 
        // array to keep track of the instances
        lazyLoadInstances.push(oneLL);
    }
});`

You will notice that Horizontally Threshold starts working but it doesn't work vertically.

Thank you.

**Comment by verlok** [comment]
Hi @weplan9,
thanks for reaching out and filing this issue.

I'm not quite sure I understood what you're trying to do here, but I forked your Codepen [here](https://codepen.io/verlok/pen/OzKBwv), created N LazyLoad instances (one for each scrolling container), and the `threshold` option is working as expected.

The only side effect is that, creating all the LazyLoad instances right away, all the images on the left are loaded at landing time. 

What you could do to solve this problem is to lazily instantiate LazyLoad instances... using LazyLoad to detect when the new scrolling containers enter the viewport.

You could read issue #29 where we discussed this technique, and eventually check [this demo](https://github.com/verlok/lazyload/blob/support/lazilyLoadLazyLoad/demos/lazily_load_lazyLoad.html).

Let me know if you need more help.
