### ISSUE TITLE
Bug: attribute changes not recognized

### ISSUE THREAD

**Issue by patric-eberle** [verlok/lazyload#190]
**What is happening?**
We are using Vue.js. In some cases the `data-src`, `data-srcset`, ... may change during runtime. This changes seem not to be recognized by lazyload. I also tried to call `.update()` but this only adds new `img`s.

**What is the expected behaviour?**
On attribute change and/or on `.update()` the `data-` properties are evaluated and the image updates.

**Which version of LazyLoad are you using?**
8.7.0

**In which browser(s) and browser version(s) are you experiencing the problem?**
Chrome (cross browser)

**Could you provide the HTML, CSS and JS code you use for your images?**
```html
<!-- example show updated data- attributes (color value was added to url) and "old" img attributes -->
<img
  data-srcset="http://via.placeholder.com/180x150/123456 180w,http://via.placeholder.com/350x150/123456 350w,http://via.placeholder.com/800x150/123456 800w,http://via.placeholder.com/1440x150/123456 1440w"
  sizes="(min-width: 1024px) 48.828125vw,(min-width: 768px) 45.57291666666667vw,100vw"
  data-src="http://via.placeholder.com/1440x150/123456" class="e-picture__image loaded"
  srcset="http://via.placeholder.com/180x150 180w,http://via.placeholder.com/350x150 350w,http://via.placeholder.com/800x150 800w,http://via.placeholder.com/1440x150 1440w"
  src="http://via.placeholder.com/1440x150" data-was-processed="true">
```

**What are the steps to reproduce the problem?**
Use a framework like Vue.js or React and update the data- properties after initialization of lazyload.

**Comment by patric-eberle** [comment]
For lazysizes there is a plugin which handles this case: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/attrchange

**Comment by verlok** [comment]
Hi Patric,
thank you for reporting this. 

It just sounds strange to me because LazyLoad doesn’t save the `data-src` nor `data-srcset` anywhere, so if it changes _before_ it’s applied to the image, the new value should be considered. 

If the image has already entered the viewport, though, the image just stops being considered by LazyLoad, since its job has been done already. 

What I advice you to do is the following: when Vue is about to change the value of the `data` attributes, if the `data-was-processesed` on the image is set to `true`, write the value in the real `src`/`srcset` attributes instead.

Does this sound feasible using Vue?

If it isn’t, you might consider using a MutationObserver like the LazySizes plugin you mentioned does. 

Alternatively, I could make the `update` attribute re-mark all the images as “not processed“, or add a new public method to do that. 

Let me know what you think. 
Thanks

**Comment by patric-eberle** [comment]
Hi @verlok 
Thank you for the response. The solution you mention with assigning the value directly to `src / srcset` would definitely work. We did this on the last project. But I think it's not the best solution, because to be able to check this, we hat do add conditions for the assignment and check if the component was rendered before.

Resetting the `data-was-processed` sounds a bit cleaner to me.

Allowing to `update()` all processed images would be the easiest to use, but probably not the most performant one I guess... Maybe an element could be given to update, and to force a "re-initialisation" of this element?

**Comment by verlok** [comment]
I checked it and it works as expected.
See [this pen](https://codepen.io/verlok/pen/zWXvKz?editors=1010) and [also this one](https://codepen.io/verlok/pen/JLVYNp?editors=1010) which uses a function to DRY the first one.

**Comment by verlok** [comment]
Hi @patric-eberle, 

I'm assuming you solved in the past months of inactivity. Feel free to reopen the issue if you still need help.
