### ISSUE TITLE
What happened to throttle?

### ISSUE THREAD

**Issue by Niresh12495** [verlok/lazyload#213]
Not a Bug, Not a Request too
May be support thread

Is there any way to throttle or set time between revealing image

**Comment by verlok** [comment]
Hi again @Niresh12495,

`throttle` was an option that one should use to make LazyLoad execute with a lower frequency the function that watches on the position of every single image. It is not an option to set time between revealing image.

The `throttle` option doesn't make sense on version __10.x__ anymore, because that function was replaced by the `IntersectionObserver API`. On version 8.x the `throttle` option still exists, but it's not in the documentation, anyway nobody was changing the value of that option and keeping the default one.
