### ISSUE TITLE
Bug: LazyLoader.loadAll does not work on 8.10.0 like it does on 10.9.0

### ISSUE THREAD

**Issue by bessey** [verlok/lazyload#220]
I am just today integrating LazyLoader into a site, for us loadAll is nice to allow deferring offscreen images just until the JS bundle has downloaded, at least on pages where being smart is tricky (e.g. images in carousels, modals, other dynamic content).

However, I found that loadAll just doesn't seem to do anything on 8.10.0. Images still load when they enter the viewport, and are not preloaded. No error, so I am confident I have the right version installed, and upgrading to 10.9.0 immediately fixes the problem, but means we lose lazyness for many browsers.

**Comment by verlok** [comment]
Thank you for reporting this issue. I will check and fix ASAP. 

In the meantime, for your specific usage, you can use version 10 since on browsers where `IntersectionObserver` is not supported, it immediately download all the images… like you would do with the `loadAll` method.

**Comment by verlok** [comment]
Hi @bessey,

I've updated the [conditional load demo](demos/conditional_load.html) in order to store the `LazyLoad` instance in the `window.lazyLoadInstance` variable.

Then I checked both on Chrome where version 10.x is loaded, and on Safari where version 8.11.0 is loaded. 

In both browsers, when executing `window.lazyLoadInstance.loadAll()` from the browser console, all the remaining images are loaded.

It seems all correct to me.
Am I missing something?

**Comment by verlok** [comment]
Hey @bessey,
I'm closing this, but feel free to open it if you have any news.

**Comment by bessey** [comment]
Strange, I really did observe a difference in behaviour, thank you for
attempting to reproduce and sorry to have wasted your time. It was far from
a minimal production, so I'm guessing I just have another issue going on,
that intersection observers handle better.

I'm ok with just supporting newer browsers so happy for this to be closed.
If the powers that be asked for further back support, I'll reinvestigate
