### ISSUE TITLE
lazyload and slick slider?

### ISSUE THREAD

**Issue by Pionell** [verlok/lazyload#228]
The lazyload does not load some photos untill they are slided to the left edge. If I have a slider with 4-5 images, some of the images are not loaded untill one of them is all the way to left side. Is there a way to get around this? The image is in the viewport but lazylaod does not see it as a image in the viewport?

**Comment by verlok** [comment]
Hi,
what you said is correct. 
To have lazy images in slick, you need to use Slick’s lazy load feature. 
See Slick demo page.

**Comment by Pionell** [comment]
I started using the slider lazylaod option when I saw this being an issue, but there are 10+ sliders in one site, and each is loaded as different elements which are optimised differently and need remaking.. I hoped there is another way of solving this. Thanks anyway. 👍

**Comment by Pionell** [comment]
I do use the version-autoload function, And the newest opera browser(which uses v8), so it should be verion 10.x but the issues seems to still be there.

**Comment by verlok** [comment]
Thanks for the update. So we'll stick to what I wrote before: you need Slick's lazy load feature. 
Happy refactoring! :)

**Comment by verlok** [comment]
BTW congrats for using Opera, it's my favorite browser too! 
I use it since the earlier versions with Dragonfly developer tools, but now that it has the same features of Chrome it's even better.

**Comment by Pionell** [comment]
I will deffenetily have fun! 😆 
I love opera because of it's messanger, snapshot, live currency translation, In-built VPN and a few other features. It's really great, and you can use chrome plugins in it (for the most part). What I miss though is the chrome's in-built translation tool..

**Comment by FlaviuRadulescu** [comment]
I have the same problem, and unfortunately slick lazy load doesn't support srcset. So I need to make lazyload work with slick. Is anyone here who could help us?

**Comment by ahmadalfy** [comment]
@ValentinCreative what you are proposing doesn't work sadly. The callback is fired yet the images arer still not updated

**Comment by FlaviuRadulescu** [comment]
I have made it work. you can see a working version here https://lumminary.com       
 $('.slide-element').on('beforeChange', function(event, slick, currentSlide, nextSlide){
            LazyLoad.update();
        });

**Comment by verlok** [comment]
@ValentinCreative, @FlaviuRadulescu, if you read the API documentation, the `update()` method only checks if newer lazy images have been added to the DOM after LazyLoad was instantiated, so there shoudn't be necessary to call that method each time a slider sled. Probably just call the method after you initialized Slick.

**Comment by Kovalchik8** [comment]
The issue is still relevant in 2023. No one mentioned that Slick clones slides on fly and that's why this library can't detect images from them without updating, so the best idea is to use native Slick lazy loading.

But consider following situation: when you want to show a part of next slide you implement it adding padding to the `.slick-list` element. Using this hack part of next slide is visible but image is not loading since Slick presumes this image is placed in next slide and triggers lazy loading after navigating to it.

**Solution #1**: set decimal number to `slidesToShow` option

`slidesToShow: 1.0001`

Now Slick will load image in next slide. But slide which is supposed to be first becomes last.

If the initial positioning of slides is important then try **Solution #2**, which is already provided above, but slightly optimized:

```
$('.slider').on('afterChange', (e, slick, currentSlide) => {
  let current_slide = $(slick.$slides.get(currentSlide))

  if (current_slide.next().hasClass('slick-cloned'))
    LazyLoadInstance.update()
})
```

The code may depend on your Slick options and how you detect there are `.slick-cloned` items in viewport. The idea is to update lazyloading only when cloned elements are visible for user.
