### ISSUE TITLE
LazyLoad + Swiper not loading cloned/duplicate slides for looping slider/swiper

### ISSUE THREAD

**Issue by cfxd** [verlok/lazyload#250]
Howdy, I love this plugin and I've been using it a lot lately. I recently came across a case where I'm using Swiper (https://github.com/nolimits4web/Swiper) in an infinite loop and can't manage to get the cloned slides to load lazily. You'll see (1) initial images load, but (2) cloned images (used to accomplish Swiper's `loop` parameter only load after you click to advance the slider.

I was hoping someone else has encountered this issue and could shed some light on the best way to ensure all the slides load correctly.

I've setup a fiddle that contains the essential elements of my use case and that displays the problem behavior:

https://jsfiddle.net/silb3r/oxb2ztu5/

**Comment by cfxd** [comment]
Actually this is still an issue on iOS devices. If anyone has some feedback it would be much appreciated!

**Comment by cfxd** [comment]
Turns out that if I add this to Swiper's `init` param before I update LazyLoad then all is well on Safari:

`$(this.$el).find('img').removeAttr('data-was-processed');`

See here: https://jsfiddle.net/silb3r/oxb2ztu5/37/ (JS line 18)

Should I be doing that?

**Comment by verlok** [comment]
Hi @cfxd
which version of lazyload you use on Safari?

**Comment by cfxd** [comment]
10.17.0

**Comment by verlok** [comment]
Sorry I tried but I couldn’t spot the version used in the fiddle from my mobile (I’m on vacations!).

So version 10.x on Safari immediately loads all images instead of loading them lazily, are you sure you want to keep using that version for all browsers?

The best way to do it would be to do a conditional loading like recommended in the readme. 

About the problem you’re having, that you solved removing the `data-was-processed` attribute, we can discuss later.

**Comment by verlok** [comment]
About lazy load of images inside a carousel slider like Swiper, Slick and others, since they don’t always actually scroll but the are moved by the sliders using CSS, you should definitely use the API provided by those scripts and avoid using lazyload there.

See how to do it for Swiper [here](
http://idangero.us/swiper/api/#lazy)

Thanks

**Comment by verlok** [comment]
Also, about using the `IntersectionObserver` polyfill, are you using the polyfill only because of LazyLoad? It would be better to use LazyLoad 8.x in this case, for a number of reasons resulting in better performance.

**Comment by verlok** [comment]
@cfxd ?

**Comment by verlok** [comment]
Assuming is solved for not receiving replies. 
Feel free to reopen.

**Comment by verlok** [comment]
Thank you @cfxd!

**Comment by verlok** [comment]
By the way @cfxd, since LazyLoad v. 10.x and v. 8.x share the same API, and v. 10 is much better for performance, you should seriously think about conditionally loading v. 8 or v. 10 depending on the browser support of `IntersectionObserver`. 

Find how to do this in the docs (README.md file).

**Comment by cfxd** [comment]
Yes I've been looking into that. Not sure it will be easy with my current gulp config but I'll see what I can come up with.

**Comment by VineetKumarKushwaha** [comment]
I am using swiper js with lazy loading and loop.
Last clonned slide does not change its data-src to src even when it is in view. Can you please suggest

**Comment by verlok** [comment]
@VineetKumarKushwaha I think the solution to this issue has been found already. Please read the discussion, particularly the latest 5-6 comments.
