### ISSUE TITLE
Plugin is failing if there is space in image name

### ISSUE THREAD

**Issue by rajeevyadav2** [verlok/lazyload#262]

**Comment by verlok** [comment]
Hi,
I need much more information in order to assess this potential bug. 
You didn’t answer any of the questions you posted. 
Please do it and reopen the issue. 
Thank you

**Comment by rbrlortie** [comment]
`data-bg="/images/my image.jpg"` fails
`data-bg="/images/my-image.jpg"` works

**Comment by verlok** [comment]
Thanks @rbrlortie,

**Comment by verlok** [comment]
Well, I took a look at the code and it's doing everything correctly.

* If you pass the background image using `data-bg` you need to wrap your image URL in a `url("...")`, because it's just copied into the `element.background.style` (so you can use multiple backgrounds).
* If you pass the background image using `data-src` you don't need to wrap it, and LazyLoad's code wraps it in `url("...")` before copying it into the `element.background.style`.

That's probably why the code reported by @rbrlortie doesn't work. And to be precise, neither one of the two options would work.

Feel free to reopen if the problem still occurs.
