### ISSUE TITLE
Lazyload responsive background images

### ISSUE THREAD

**Issue by salespageshark** [verlok/lazyload#263]
I use different background images depending on the user's screen size. For example for sm and lg screen sizes in a bootstrap framework I load different background images in CSS for better performance. I also load different images for pixel ratio 2. Would it be possible to add a feature to load responsive background images? Thanks!

**Comment by verlok** [comment]
Hi and thank you for your suggestion. 

LazyLoad’s mission is to offload the loading of below-the-fold content images which can also be responsive images. 

LazyLoad also supports background images as a list of URLs, but I think this is the limit of what it will do for background images.

**Comment by verlok** [comment]
Think of background images as images that can be removed in the printed version of the page (which is what browsers do), and content images as images that the user would like to print. 

What kind of images are you developing for?

If the images you’re loading are meaningful to the user and not just “background”, you should definitely use responsive images through the `img` tag instead of using background images.

See “responsive images” on google.

LazyLoad supports both simple `img` with `srcset` and `sizes` attributes, and the `img` surrounded by the `picture` tag. 

See the demos folder for examples.

**Comment by verlok** [comment]
Hey @salespageshark,
things changed on version 15. 

I found a way to manage background images's load/error event, so now background images are now getting the `loaded` or `error` class and calling `callback_loaded` and `callback_error`.

Take a look at the [changelog](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md) and to the [upgrading guide](https://github.com/verlok/lazyload/blob/master/UPGRADE.md) if you're interested.

Also I will be soon releasing a feature to load 1x or 2x background images as of #425, so stay tuned.

Have a nice day.
