### ISSUE TITLE
Bootstrap Modal not working

### ISSUE THREAD

**Issue by psion** [verlok/lazyload#264]
I cannot seem to get the images to load in a modal in Bootstrap.  I'm using version 8.16.0 in Chrome.

```
<div id"image-modal" class="modal">
    <div class="modal-body">
        <div class="image"><img data-src="image.jpg"></div>
    </div>
</div>
```

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/8.16.0/lazyload.min.js"></script>
<script>
    var myLazyLoad = new LazyLoad();
</script>
```

I tried through the console my.LazyLoad.loadAll() and all the images loaded.

EDIT:  Added code blocks

**Comment by verlok** [comment]
Hi @psion,

it probably doesn't work because the modal is a separate container from the main scrolling container which is the page body (document element).

If you want to make it work, you should create a separate lazyload specifying a different `container` in the option, corresponding to the scrolling container in the modal.

But before doing that, could you explain to me why would you need to lazyload images in a modal? I mean why don't you use the real `src` attribute for that image so that the images is loaded natively by the browser when the modal appears?

**Comment by verlok** [comment]
@psion are you still there?
