### ISSUE TITLE
Loading uneeded images with flex

### ISSUE THREAD

**Issue by jakubkaderavek** [verlok/lazyload#269]
Hi,

we found bug in plugin - you can see there https://codepen.io/jakubkaderavek/pen/pxBQpo
This bug is made be CSS - exactly in class .swiper-wrapper we have css  display: flex;
and in class .swiper-slide we have  flex-shrink: 0;
When we remove one of this class the is everything ok - problem is only with hidden images (images in right)

Thank for fixing

**Comment by verlok** [comment]
Hi @jakubkaderavek,
thanks for reporting this, but I think this is not a bug.

Version 8.x of LazyLoad shouldn't be used to lazy load images in sliders, it's to be used only with images that enter the viewport upon a `scroll` or `resize` event, like the user scrolling or resizing the window.

I assume that version 10 can do the trick because it uses IntersectionObserver, but I'm not absolutely sure (it depends on the slider you're using).

The proper way to lazily load images inside Swiper is to use Swiper APIs. See [Lazy loading with swiper](https://www.tutorialdocs.com/tutorial/swiper/api-lazy-loading.htm).

Thank you.

**Comment by verlok** [comment]
There are a number of other similar issues on this repo, you can find them [here](https://github.com/verlok/lazyload/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+slider).

**Comment by jakubkaderavek** [comment]
Hi @verlok,

thank for the fast reply!
After detail checking our code I found a bug in another place - there are two similar pages:
https://wpjakub.cz/lazyload.html
https://wpjakub.cz/lazyload-opacity.html
Its white space 1500 px height with slider bottom (only CSS without any JS). 
When I load first, then is everything ok.
Second load some hidden images after page load with no scrolling.

lazyload-opacity version have only this CSS moreover:
```
 .lazyload {
  opacity: 0;
}
.lazyload.loaded {
  opacity: 1;
}
```
Thank you for your help

**Comment by verlok** [comment]
I can’t see anything on the pages you linked. Totally white. 

Anyway I read that you’re using a slider bottom with CSS. Did you initialize LazyLoad passing the scrolling container in the `container` option?

PS: If you have 2 different scrolling containers, the window and a CSS scrolling containers, you need 2 instances of LazyLoad

**Comment by jakubkaderavek** [comment]
@verlok 
there is blank div before slider - I prepare you two videos explain where the problem is:
https://www.wpjakub.cz/lazyload.mov
https://www.wpjakub.cz/lazyload-opacity.mov
In the second you see, that images are loaded right after reloading page - as I said, the only difference is in CSS with opacity which is very strange. In first video is everything ok

**Comment by jakubkaderavek** [comment]
@verlok I found, that this bug is only in Chrome so i report it. In Firefox and Safari is everything ok.

**Comment by verlok** [comment]
Ok so @jakubkaderavek it seems this is a Chrome bug. Did they already solve it?

**Comment by jakubkaderavek** [comment]
Hi @verlok , I test it in new Chrome and everything looks ok
