### ISSUE TITLE
Failed to construct 'IntersectionObserver': member root is not of type Element.

### ISSUE THREAD

**Issue by DMCK96** [verlok/lazyload#273]
* What is happening?
Uncaught TypeError: Failed to construct 'IntersectionObserver': member root is not of type Element.
    at LazyLoad._setObserver (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:72065)
    at new LazyLoad (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:72030)
    at initLazyLoad (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:10843)
    at Object.finalize (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:9883)
    at Object.fire (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:10803)
    at HTMLDocument.loadEvents (bloc.js?v=8D0F1A6747196AF933F5FA40C1948C1D:10812)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

* What is the expected behaviour?
To not be getting the above type error, as root has not been set anywhere so should be defaulting to using the top level document element.

* Which version of LazyLoad are you using?
10.19.0

* In which browser(s) and browser version(s) are you experiencing the problem?
Chrome 70.0.3538.77 and Firefox 62.0.3

* Could you provide the HTML, CSS and JS code you use for your images?
JS
```js
import LazyLoad from "vanilla-lazyload/dist/lazyload";

export function initLazyLoad() {
  const lazyLoad = new LazyLoad({
    elements_selector: '.lazy'
  });

  const lazyLoadContainer = new LazyLoad({
    container: '.lazy-container'
  });
}
```

This error occurring on every page (even those without images) So I don't think it's caused by the HTML syntax. 

* What are the steps to reproduce the problem?
1. Load above JS script and execute initLazyLoad. 
2. Script errors.

Thank you.

**Comment by DMCK96** [comment]
Issue was caused by container expecting an element as the variable rather than a string (confusion due to how elements_selector works). 

So replace '.lazy-container' with document.getElementById('lazy-container')

In my use case due to having numerous containers I have an array of elements looking for lazy-container and then wrap the constructor in a foreach loop.

**Comment by vcoppolecchia** [comment]
### My context
I inserted lazyload script the async way and [with this recipe](https://www.andreaverlicchi.eu/lazyload/#conditional-load)("_conditional load_").

### What is happening
I get the same error as @DMCK96. Essentially my page loads lazy images the right way, but in the console I get this:
![verlok-lazyload-issue](https://user-images.githubusercontent.com/900011/49229351-99ec5080-f3ed-11e8-9104-2a0d06bc38a7.jpg)

### Which version of LazyLoad I'm using
I'm conditionally loading based on browser capabilities, just like is suggested in the recipe "_conditional load_".

### HTML, CSS and JS code I'm using
The recipe has only a single difference from the standard one in the documentation: I'm passing to window object an array of `lazyLoadOptions` options. The only reason I'm doing so is because I am lazy loading also other images in the page (other than those in the HTML markup below).

Script and options
```html
<script>
  (function(w, d) {
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement('script'); 
    var v = !('IntersectionObserver' in w) ? '8.17.0' : '10.19.0';
    s.async = true;
    s.src = 'https://cdn.jsdelivr.net/npm/vanilla-lazyload@' + v + '/dist/lazyload.min.js';
    w.lazyLoadOptions = [{
      elements_selector: '.lazy-img'
    }, {
      elements_selector: '.lazy-img',
      container: document.querySelectorAll('.scrollable-small-only')
    }];
    b.appendChild(s);
  }(window, document));
</script>
```

The HTML
```html
<ul class="scrollable-small-only">
...
<img class="lazy-img" data-src="path/to/the/image.jpg" alt="..." />
...
</ul>

```
Any help will be of great benefit, thanks.

**Comment by verlok** [comment]
@vcoppolecchia did you manage to understand why you were getting the error? 
And in what browser did you get it?
If you still need help, please reproduce the issue on [codepen](https://codepen.io) and I will be able to help you.
