### ISSUE TITLE
lazyload and isotope issue

### ISSUE THREAD

**Issue by AdelDima** [verlok/lazyload#276]
I'm using Isotope with ["packery" layout mode](https://isotope.metafizzy.co/layout-modes/packery.html).
Isotope will calculate the potion of the Images depending on image size, but with LazyLoad with `src` and `srcset ` attribute blank (  or with a placeholder ) isotope will calculate potions from the placeholder and this is the result https://d.pr/i/wpzIcV

I tried to use `update()` and `loadAll ()` method before calling isotope but it won't work.

Test with 8.x and 10.x on Chrome and Firefox.

The code we are using:
```js
let myLazyLoad = new LazyLoad({
            elements_selector: ".js-lazy-image, .js-lazy-image-css",
            class_loading: "lazy-loading",
            class_loaded: "lazy-loaded"
 });
```
Any help will be appreciated. 
Thank you.

**Comment by AdelDima** [comment]
In order to fix this issue, I hade to reupdate isotope layout after I called isotope, and here is the code if someone needs a solution:

```
                    let $imgs = $container.find("img.js-lazy-image");

                    $container.imagesLoaded(() => {

                        $container.isotope(params);
                        if (pxdm_js.is_lazy_image) {
                            $imgs.load(function () {
                                $container.isotope('layout');
                            });
                        }

                    });

```

**Comment by verlok** [comment]
Hi @AdelDima,
I'm sorry that I'm so late in replying but I've been very busy in the latest days.

That's a good question, I think that LazyLoad doesn't work very well with Isotope because Isotope tries to read the image size before they're loaded. 

- The `.update()` method won't work because it just tells LazyLoad to check for more images that might have been added to the page in case of pagination, dynamic content, etc.
- The `loadAll()` loads all the images, but is in a asynchronous operation so it would take time, and anyway if you loaded all the images, why bothering using LazyLoad?

If the image sizes are known before loading, have you tried specifying the image sizes in-line via CSS of HTML?
