### ISSUE TITLE
srcset in picture element

### ISSUE THREAD

**Issue by pkjoshi** [verlok/lazyload#284]
Are you reporting a bug or requesting a feature?
I believe it is a bug, if I am not doing something wrong

If it's a bug, it would be very useful to me if you answered the following questions.
Your answers will help me understand what's happening and enable me to reproduce the bug.

* What is happening?
The image from data-srcset is not used, instead, only the default image is being used.
* What is the expected behaviour?
It should behave as if we are not using lazyload and the appropriate image is loaded depending upon media width or browser
* Which version of LazyLoad are you using?
https://cdn.jsdelivr.net/npm/vanilla-lazyload@10.19.0/dist/lazyload.min.js
* In which browser(s) and browser version(s) are you experiencing the problem?
I checked in firefox and chrome
example 
![image](https://user-images.githubusercontent.com/1332106/50058917-8a1e8b80-01a5-11e9-86ee-9362d3db933a.png)
it should have loaded Categ_01_480.jpg in firefox and Categ_01_480.webp in chrome.
* Could you provide the HTML, CSS and JS code you use for your images?
```
<picture>
<source media="(max-width: 320px)" data-srcset="{{media url="wysiwyg/panel/Categ_01_320.webp"}}" type="image/webp">
<source media="(max-width: 320px)" data-srcset="{{media url="wysiwyg/panel/Categ_01_320.jpg"}}" type="image/jpeg">
<source media="(max-width: 480px)" data-srcset="{{media url="wysiwyg/panel/Categ_01_480.webp"}}" type="image/webp">
<source media="(max-width: 480px)" data-srcset="{{media url="wysiwyg/panel/Categ_01_480.jpg"}}" type="image/jpeg">
<source media="(min-width: 481px)" data-srcset="{{media url="wysiwyg/panel/Categ_01.webp"}}" type="image/webp">
<source media="(min-width: 481px)" data-srcset="{{media url="wysiwyg/panel/Categ_01.jpg"}}" type="image/jpeg">
<img class="lazy" style="width: 100%; height: auto;" data-src="{{media url="wysiwyg/panel/Categ_01.jpg"}}" />
</picture>
```
* What are the steps to reproduce the problem?
I don't think any other step is necessary. lazyload is working but srcset is not working.
Thank you.

**Comment by DimLeon** [comment]
Hello @pkjoshi. Try to include a width descriptor (or a pixel ratio descriptor) in each of your data-srcsets.
For example: data-srcset="wysiwyg/panel/Categ_01_320.webp 320w" 
(or data-srcset="wysiwyg/panel/Categ_01_320.webp 1x").
I remember having some similar issue as well with <picture> and lazyload and for some reason it worked by using a width descriptor.
Also, try to change the media attribute "(max-width: 480px)" into:
"(min-width: 321px) and (max-width: 480px)",
in order to be more explicit for the browser's pick.
I hope this will work for you

**Comment by pkjoshi** [comment]
Hi @Demleon - Thanks for your suggestion, but without adding width descriptor or pixel ratio it's working fine, like correct image version is served depending on the browser or media width. There is no issue whatsoever.
I face the issue only when I am using lazyload. 
so do you think that adding pixel ratio will help in resolving this?

**Comment by verlok** [comment]
Hi @pkjoshi,

no, the descriptors are not required in the `srcset` attribute, as you can see in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

**Comment by verlok** [comment]
@pkjoshi have you checked what's in the `source` tags DOM after the images entered the viewport? The `data-srcset` attributes should have been copied to the `srcset` attributes both in the `img` and in the `source` tags. If that happened, it's not a problem of the LazyLoad script. If it didn't happen, it is.

I'm pretty sure my script is working because I'm testing it right now in the `demos/with_picture.html` demo. Check this out online [here](https://www.andreaverlicchi.eu/lazyload/demos/with_picture.html).

Let me know.

**Comment by verlok** [comment]
I’ve reviewed the README documentation and updated the demos under the `demos` folder. Please take a look there. If you still need help, feel free to reopen.
