### ISSUE TITLE
to add to_webp functionality to loadAll() function

### ISSUE THREAD

**Issue by rsdsoft** [verlok/lazyload#302]
Is it possible to add to_webp functionality to loadAll() function? if to call it now it loads images with default files extensions.

I am using this way:

```js
    (function(w, d){
            var b = d.getElementsByTagName('body')[0];
            var s = d.createElement("script"); 
            var v = !("IntersectionObserver" in w) ? "8.17.0" : "10.20.0";
            s.async = true; // This includes the script as async. See the "recipes" section for more information about async loading of LazyLoad.
            s.src = "https://cdn.jsdelivr.net/npm/vanilla-lazyload@" + v + "/dist/lazyload.min.js";
            w.lazyLoadOptions = {
                 elements_selector: ".lazy"            
                 ,to_webp: true
             };
            b.appendChild(s);
        }(window, document));

window.addEventListener('LazyLoad::Initialized', function (e) {
            lazyLoadInstance = e.detail.instance;
            lazyLoadInstance.loadAll();
        }, false);
```

**Comment by verlok** [comment]
First of all, why do you use LazyLoad if you load all the images as soon the library gets initialized?

Anyway, what you're doing should be already working, since the file extension is replaced to `.webp` in before copying the image source from the `data-` attributes to the actual ones, and this doesn't depend on whether this operation is triggered by a `load()` call, a `loadAll()` call, or an image entering the viewport.

So I might need more information from your side in order to understand what's going wrong with your implementation.
