### ISSUE TITLE
Using with imgcache plugin

### ISSUE THREAD

**Issue by an-rahulpandey** [verlok/lazyload#32]
Hi,
Can we use it with this - 

https://github.com/chrisben/imgcache.js

There is a already a way for lazyload plugin
https://github.com/chrisben/imgcache.js/issues/167

**Comment by verlok** [comment]
Hi, thank you for your question. 
You should ask the author os imgcache I guess :)
@chrisben what do you think?

**Comment by an-rahulpandey** [comment]
Thanks, I have opened the issue here - 
https://github.com/chrisben/imgcache.js/issues/173

Also was wondering if we can load the image in synchronous order?

**Comment by verlok** [comment]
What do you mean by "synchronous order"? The order in which they are in the DOM? I think you can START loading them in that order (it should already work like that) but of course you can't control when the load event will happen, because it depends on many factors (image weight, network conditions, etc).

**Comment by an-rahulpandey** [comment]
Yes, by synchronous I mean the order in which they are listed in DOM. sometimes images at the bottom of page view load first, then the top images. Or sometimes first two images get loaded and then bottom images, and then middle page images.

**Comment by verlok** [comment]
I'm afraid you can't control which images load first.
