### ISSUE TITLE
All images loaded on page load in Safari, IE

### ISSUE THREAD

**Issue by peterdarthur** [verlok/lazyload#328]
**Describe the bug**
When loading a lazy-enabled page in Chrome, Firefox, or Edge, images load when threshold is met, as expected.
When loading a lazy-enabled page in **Safari, IE11** (and probably IE10), all images load ('loaded' callback) on page load.

**To Reproduce**
1. Open a lazy-enabled page in Chrome, verify that it loads images with scrolling. (sample pen: https://codepen.io/peterdarthur/pen/pYwJZv )
2. Open the same lazy-enabled page in Safari or IE11 and see that all images load on page load.

**Expected behavior**
Safari and IE11 should not load images on page load, but on scroll, as they do in Chrome, FF, Edge

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 11.0.3

**Desktop (please complete the following information):**
 - OS: Mac 10.13.4
 - Browser: Chrome 73.0.3683.75 , Firefox 65.0.2, **Safari 11.1**

 - OS: Windows 10 Pro 1809
 - Browser: Microsoft Edge 44.17763.1.0, Chrome 73.0.3683.75, Firefox 56.0, **IE 11.379.17763.0**

**Comment by verlok** [comment]
Hey @peterdarthur,
thank you for opening this with such precision.

This is why IE and Safari don't [support IntersectionObserver](https://caniuse.com/intersectionobserver), and you didn't load the polyfill before LazyLoad.

Currently, you will need to load the polyfill but in a couple of weeks it won't be _that_ necessary anymore, since **Safari is going to support IntersectionObserver in the very next version**, so only IE stays out of the game (but they will see all the images anyway, don't they?).

Please read the [Getting Started - Script](https://github.com/verlok/lazyload#-getting-started---script) section of the README file for more information.

Are you satisfied with the answer?

**Comment by peterdarthur** [comment]
Thank you for your thorough answer! I will try the polyfill.

**Comment by SteveQ88** [comment]
I have this same issue and I am loading the polyfill first. If I scroll down the page and refresh then scroll back up the lazy load/ intersection observer works fine but if I load the page at the top of the document then scroll down everything has already loaded. Any thoughts on what could be causing this would be very much appreciated :) Thanks for an awesome repo this is a great module 😀

**Comment by verlok** [comment]
My guess is: LazyLoad is executed before the Polyfill for some reason. 

Try and debug your website and see if this is true.
