### ISSUE TITLE
Setting the sizes attribute automatically

### ISSUE THREAD

**Issue by richgcook** [verlok/lazyload#344]
Is there any news to be able to use data-sizes="auto" (much like you can with https://github.com/aFarkas/lazysizes)?

> lazysizes supports setting the sizes attribute automatically, corresponding to the current size of your image - just set the value of data-sizes to auto.

**Comment by verlok** [comment]
Hi @richgcook, thank you for asking.
I don't plan to do it, right because LazySizes does exactly that and I don't  want to duplicate that library.
This lazyload is meant to manage lazy loading only, and stay small and lean.

**Comment by richgcook** [comment]
Thanks for the reply, @verlok. That's totally understandable. Probably not a hard thing to write myself, to be honest.

**Comment by verlok** [comment]
Please mind that the `sizes` attribute is meant to be put in the HTML because the browser needs to know the size of the image in advance (before loading and executing JS, and even before loading and parsing CSS) so that it can pick the right image source to download amongst the ones you list in the `srcset` and start download that as soon as possible. 

Placing the `sizes` attribute after the `srcset` is set would probably result in a double network request: the first  when LazyLoad sets the `srcset`, the second when you set the `sizes`.

I’d tell you to use lazysizes if you want it to be calculated automatically, but you’d still need to calculate it manually and put it in the html code for the first images that are “above the fold” (because if you lazy load all the images in your page instead of only the below the fold ones, you would delay all image loading and slow down your website). 

So the best thing to do is to put the `sizes` attribute in the HTML just like the spec says. :)

**Comment by PubliAlex** [comment]
It can be useful when the image can be edited by the final (non technical) user and you don't know in advance what will be the size of the chosen image. This is something I encounter everyday and, even if I personnaly prefer you script, but will always be stuck with lazysizes as it seems the only library to provide this feature.

**Comment by verlok** [comment]
@PubliAlex so the final user is able to change the layout of the website, is that correct? 

Because the `sizes` attribute specifies how much space the image takes on the page, not the size of the uploaded image.

**Comment by PubliAlex** [comment]
@verlok Sorry my post was not clear. When I talk about the size of the image, I mean aspect ratio. Let's imagine an administrable website where the final (non technical) user can change some image. You can't know what will be the aspect ratio of the image, and so, you can't fill the "sizes" attribute, manually.

In my situation, it's a very common case because the core job of our agency is to build website easily administrable by the client, and, in that situation, havine some JS that automatically calculate the size of the image is a real time saver.

That's why I think your plugin could have a lot of benefits and more adoption if it could handle this, because, for most other cases, it's better than lazysizes, but I think that small but required features make that a lot of people stay with lazysizes. It's my case, and I'm probably not alone

Best regards,

**Comment by verlok** [comment]
Thanks for your reply @PubliAlex. 

But again, I need to ask the same question: is the final user able to change the layout of the website, or just upload an image with different ratio, but the width of the image is defined by designers?

Because the `sizes` attribute specifies the width, not the height nor the aspect ratio of the uploaded image.

**Comment by PubliAlex** [comment]
Hello,

Sorry for the late reply, I forgot that thread.

Yes, actually, the final user can change the layout of the website sometime. Let's imagine if you give him some options to defined the number of element per row in a grid.

I imagine it would be doable to calculate the sizes attribute depending on the number of image per row the user define, but it can take you some hours to handle all the possible cases when define a data-sizes attributes take you about 2 seconds.

I'm not agree with the fact that adding this to vanilla lazyload is useless cause it mimic what is already done with lazysizes. I don't really want to return to lazysizes because I prefer the approach of vanilla lazyload in almost all others aspects. I just want to see the only thing I love in lazysizes ported to lazyload to have the best possible tool.

To make it light, I think it could be an activable option, set to false by default, when you initialize lazyload. Something like this : 

        window.lazyLoadInstance = new LazyLoad({
           autoSizes: true, // New option to activate automatic sizes calculation by defining a data-sizes attribute.
        });

It would be a.w.e.s.o.m.e

Best regards,

**Comment by verlok** [comment]
Thanks for explaining. 
to dynamically define the sizes attribute like lazy sizes do has always been out of the scope of my LazyLoad library. 
It's supposed to be a library to speed up the loading of web pages, and what you suggest would require JavaScript to be executed also for the above-the-fold part of the page. As a result, it would slow down the rendering of above-the-fold images. 
This is why I never implemented this feature.

**Comment by PubliAlex** [comment]
@verlok I completely understand your point, and that's why I switcher from lazysizes to vanilla lazyload.

That's why I propose the idea to implement the feature, but to consider it as disabled by default, with the option to manually enable it when you initialize vanilla lazyload.

Because, even if I'm agree with you in the theory, in the real world, sometimes, for small, low budget projects, it's a time saver to be able to automatically calculate the sizes attributes and it would be aweome to be able to do it with vanilla lazyload instead of being obliged to switch library depending on the need.

I think that many developpers still use lazysizes because of this feature, myself included for low budget projects whereas vanilla is better overall, it's a shame.

But you are the boss, boss. I dont want to dictate where you should go with your plugin, just to bring some use cases where the feature would be useful and make sense.

Best regards, and thank you for this awesome plugin !

**Comment by verlok** [comment]
Thanks for the additional point of view.

> in the real world, sometimes, for small, low budget projects, it's a time saver to be able to automatically calculate the sizes attributes and it would be aweome to be able to do it with vanilla lazyload instead of being obliged to switch library depending on the need.

I guess if lazysizes does that, and it does it well, there's no need to add the feature to my library, which has become stable and I wouldn't like to make unstable with a new feature that potentially require a lot of work and calculations.
