### ISSUE TITLE
Auto Switch to Webp

### ISSUE THREAD

**Issue by BadgersNadgers** [verlok/lazyload#348]
Just found the answer to previous question

**Comment by verlok** [comment]
Hello, thank you for asking. 

This is exactly what happens: we introduced the feature in the previous versions but we found out that it’s useless because you can automatically switch to what do you think your HTML code. hello, thank you for asking. This is exactly what happened: I introduced the feature in the previous (< 11) versions but we found out that it’s useless because you can automatically switch to Webp just using your HTML code. 

You can find more information in some of the closed issues if you search for closed issues and webp.

**Comment by verlok** [comment]
You can look precisely at #288

**Comment by verlok** [comment]
Also, please remind that you should NOT use lazy load to load the above-the-fold images of your page, since it’s a bad practice for performance.  

So if the switch the webP would be made by the lazy load script you would have WebP only in the below-the-fold images which are not that important to the perceived performance of your website.

**Comment by BadgersNadgers** [comment]
Thanks for your reply.
Much appreciated
