### ISSUE TITLE
Load image when image center hits bottom of viewport or center of viewport

### ISSUE THREAD

**Issue by richgcook** [verlok/lazyload#353]
Is it possible to load the image when the center of the image either a) hits the bottom of the viewport b) is in the center of the viewport? I thought we could've used negative values on the threshold but it doesn't work.

**Comment by verlok** [comment]
No it can’t work using negative threshold values. 

To use this feature you should probably tweak the real thresholds of intersectionObserver, but they are hardcoded here. 

But first: what do you need this for?

**Comment by richgcook** [comment]
For design the images load before I get to them and I have an effect (transform up slight, scale from 0 to 1 and opacity from 0 > 1) for when they're loaded but you never see it as it happens 'offscreen'.

**Comment by verlok** [comment]
Cool. 

You can use the `callback_enter` option to pass a callback to be executed only when the image has actually entered the viewport. In the callback, you can trigger any effect you want. 

Or you can delay the loading of the image using the `load_delay` option. 

I’d recommend the first solution because it would improve the perceived speed, since the images would still start loading off viewport.

**Comment by richgcook** [comment]
Perfect, that all makes sense. Thanks!
