### ISSUE TITLE
Safari - Class loading/loaded not working

### ISSUE THREAD

**Issue by marcelaerts** [verlok/lazyload#421]
**Describe the bug**
I'm using the latest version of the plugin but for some reason my images are not loading on Safari. The img has the class of loading. Chrome and Firefox work fine.

**Expected behavior**
The class should change into loaded.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 13.0.1

**Desktop (please complete the following information):**
 - Device: iMac
 - OS: macOS Catalina
 - Browser: Safari
 - Version: 13.0.05

**Comment by verlok** [comment]
Hey there. Thank you for reporting this. Could you please add more detail reporting the HTML, JS and CSS code you’re using?

**Comment by marcelaerts** [comment]
I was using this:
<img alt="A lazy image" src="lazy-lowQuality.jpg" data-src="lazy.jpg" />

When I removed the src tag it worked. But the problem only appears in Safari.

**Comment by graememscott** [comment]
I was having this same issue. I think it was due to me initializing the plugin after "DOMContentLoaded"

```
document.addEventListener("DOMContentLoaded", function() {
  lazyLoadInstance = new LazyLoad({
    elements_selector: "img"
  });
});
```

When I changed the event to "load" on the window, it worked!

```
window.addEventListener("load", function() {
  lazyLoadInstance = new LazyLoad({
    elements_selector: "img"
  });
});
```

**Comment by verlok** [comment]
Hey there,

@marcelaerts 
> When I removed the src tag it worked. But the problem only appears in Safari.

Thanks for the additional information. This seems to me a bug of Safari not firing the `load` event on the images after the `src` attribute has been changed via Javascript. I'll make some tests and I'll let you know.

@graememscott 
> When I changed the event to "load" on the window, it worked!

This delays the initalization of LazyLoad for a long time, since the page load event could be fired very late in time. Are you satisfied with the overall performance of this solution?

**Comment by graememscott** [comment]
@verlok it would be nice to initialize LazyLoad sooner, as I don't have this same problem in Chrome

For me, the site I'm working on loads really fast so it's not an issue. I just worry for others with slower internet, like you said they may have to wait a while since the page load event could take a while to fire.

**Comment by verlok** [comment]
Hey @marcelaerts ,

I tested [this demo page](https://www.andreaverlicchi.eu/lazyload/demos/image_ph_external.html), which has a placeholder image in the `src` attributes and a lazy image in the `data-src` attribute, and **I couldn't reproduce the bug you reported** neither on Safari nor other browsers.

See this screenshot
![image](https://user-images.githubusercontent.com/1127721/76634625-afd04700-6546-11ea-9c51-1f6feb552dd1.png)

I assume that you are having this problem because you're initializing LazyLoad _before_ your placeholder images have been loaded.

One solution could be the one reported by @graememscott , if it's acceptable to you.

Another solution, which would be even better for browser performance optimization, would be to avoid using placeholder images in the `src` of the images. If you could tell me what is the reason why you are using placeholder images, I could help you find an alternative solution.

**Comment by verlok** [comment]
@marcelaerts feel free to reopen if you still need help
