### ISSUE TITLE
Lazy load not loading images visible in the viewport

### ISSUE THREAD

**Issue by omarel1** [verlok/lazyload#423]
I'm loading images with a json file using jquery's $getJSON() and adding the image url in the data-src attribute. For some strange reason, It does load images on scroll that enter the viewport, but not loading images that are viewable in the viewport on page load. I even tried lazyLoadInstance.update(); but nothing.

Has anyone seen this before.

**Comment by omarel1** [comment]
The source of the issue of the conflict is that I'm adding url to the data-src attribute with jquery after the page loads, but the lazyLoadInstance.update() doesn't help in this case when the image is already in the viewport.

**Comment by verlok** [comment]
Hey there,
The reason is that the  images that are in the viewport have already been processed from LazyLoad, and it won’t check them again to optimise performance. 

The `update` method is only useful to detect new elements that have been added to the DOM, not to re-check images that have already been processed from LazyLoad. 

The way that LazyLoad uses to check whether or not it has  already processed an image is to check the `data-was-processed` element. So the hack for you would be the following. 

**When you set the `data-src` using jQuery, also make sure you delete the `data-was-processed` attribute** 

This should fix your issue

**Comment by verlok** [comment]
Any luck?

**Comment by omarel1** [comment]
hmm, that didn't work for me. Same thing, when you load the page, what's already in the viewport doesn't show, but as you scroll, the images show up. Here's some screenshots where I'm replacing content dynamically in a function and what the element looks like on inspecting
<img width="474" alt="Screen Shot 2020-03-17 at 8 45 09 PM" src="https://user-images.githubusercontent.com/6363878/76914620-3c556f00-6891-11e
<img width="618" alt="Screen Shot 2020-03-17 at 8 44 56 PM" src="https://user-images.githubusercontent.com/6363878/76914629-424b5000-6891-11ea-9af4-77b8f8480534.png">
a-98bc-44b82c4d69bf.png">

**Comment by omarel1** [comment]
I just added lazyLoadInstance.update(); into that function and now it works! So the hack of removing data-was-processed and adding the update() method worked when combined in my instance.

Any downsides to this?

**Comment by verlok** [comment]
Great!
