### ISSUE TITLE
Using "use_native" breaks lazy bg loading

### ISSUE THREAD

**Issue by stevesy** [verlok/lazyload#439]
**Describe the bug**
When setting "use_native" to true, lazy background image loading no longer works. No error is presented.

**LazyLoad version**
- Version 15.1.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by verlok** [comment]
Hey @stevesy, thank you for opening this.

That's because the _native_ lazy loading of background images doesn't exist in browsers.
So if you want to user native lazy loading for content images and JS-based lazy background images, you need to create 2 instances of LazyLoad, with 2 different set of options.

```js
// Suppose your lazy content images have the class "lazy" applied
const lazyContent = new LazyLoad({ elements_selector: "img.lazy", use_native: true });
const lazyBackground = new LazyLoad({ elements_selector: "div.lazy" });
```

**Comment by stevesy** [comment]
I understand this, but it was working before v15.

**Comment by verlok** [comment]
The library went through an important code refactoring.
Refactoring can lead to unexpected breaking changes like this. 
That's why I released it under a new major version.

You have 2 options:
- create 2 instances of LazyLoad, with 2 different set of options.
- keep using v. 14
