### ISSUE TITLE
Http Request for Image occuring twice with null value returned for subsequent request

### ISSUE THREAD

**Issue by irejwanul** [verlok/lazyload#48]
Hi, Thanks for your very useful package. But, I don't know how its happening, its always making two HTTP request to the server for image, and either for first call or the subsequent call, its taking more time and response coming 'null'. And, at the same time image is loading on selector_elements.

**Comment by verlok** [comment]
Thanks @irejwanul,
can you please post the HTML and JS code you're using?

**Comment by verlok** [comment]
And maybe the version of the script you're using, if this is still an issue.

**Comment by Niresh12495** [comment]
Well i think Im experiencing the same issue
script is adding `style="background-image: url("null");` inline style to all div & a tags 
Here is an example page 
[Guest Blog](https://www.guest.blog/)
[How to be happy](https://www.guest.blog/post/7043/be-happy/)

Please add a random variable to end because the pages are cached

**Comment by Niresh12495** [comment]
Fixed: This is the small change made
`if (elementSrc) element.style.backgroundImage = "url(" + elementSrc + ")";`

:)

**Comment by verlok** [comment]
Thanks @Niresh12495 
Just released 4.0.4 (version not found 🤣)

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
