### ISSUE TITLE
How to use lazy load with Bootstrap modal?

### ISSUE THREAD

**Issue by anchev** [verlok/lazyload#50]
I am using this theme:

https://startbootstrap.com/template-overviews/agency/

and in `agency.js` I added:

```
var lazyLoad = new LazyLoad();
$('.modal').on('shown.bs.modal', function () {
    lazyLoad.update();
});
```

but the problem is that when the modal which contains many images is opened all of them get loaded instantly. I would like them to load lazily, i.e. when scrolling down.

How can I do that?

**Comment by anchev** [comment]
In fact I notice that the last few images in the modal often don't show unless the window is resized, moved or the view is zoomed in/out using Ctrl and +/-

**Comment by verlok** [comment]
Hi @anchev and thanks for choosing my LazyLoad.

If I understood correctly, the images you want to load lazily are inside the modal you are opening via javascript, and the modal has a scrolling panel inside it.

If so, you need to initialize a new LazyLoad when the modal is shown, and pass the scrolling container in the `container` option.

Something like:

```js
$('.modal').on('shown.bs.modal', function () {
    var lazyLoad = new LazyLoad({
         container: $(this) /// <--- not sure if this works here, read below
    });
});
```

In the `container` you need to pass the element that scrolls (so the one that has the `overflow` property set to scroll or auto).

You could also call `lazyLoad.destroy()` when the modal is closed, in order to save memory and do everything properly.

**Comment by anchev** [comment]
Thanks for the reply. However it seems to me I didn't explain correctly.

I want to have lazy load both on the main page, as well as in the modals. So as far as I understand the lazyLoad object must be created initially (right?) Then the question is how to make it work also for the modal.

I hope that clarifies what I am looking for.

**Comment by anchev** [comment]
I think I figured it out:

```
var globalLazyLoad = new LazyLoad();

var modalLazyLoad;
$('.modal')
        .bind('shown.bs.modal', function () {
            modalLazyLoad = new LazyLoad({
                container: this
            });
        })
        .bind('hidden.bs.modal', function () {
            modalLazyLoad.destroy();
        });
```

It seems to work. Could you please confirm if this is the right way to do it?

**Comment by verlok** [comment]
Yess!!! That's correct. Congratulations.

**Comment by anchev** [comment]
Thank you!

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)

**Comment by jakeman1031** [comment]
I'm working on getting this modal to work the same way. Cant seem to get it working with the same code. Can I re-open this?
