### ISSUE TITLE
CSS class for inital viewport images

### ISSUE THREAD

**Issue by zedL** [verlok/lazyload#58]
Hello,

I want to fade in my lazy loaded images. I can do this with the loaded class.
But than the inital load of my view fade in all image elements. I found that is ugly. I only want to fade in images when the user scrolls or resize the browser.
Is it possible to introduce a new class called first-load on images that are loaded when the view renders the first time (or lazyload runs the first time) ? Or vise versa on images that are lazyloaded after the first inital run.

Thanks a lot.
René

**Comment by verlok** [comment]
Hi @redL,
Thank you for your suggestion.  Unfortunately it's not possible to do what you suggest, because I can't distinguish which images are inside did you put initially and which ones are outside. 
In fact, the script runs independently when the user scrolls or resizes the window or at the first load of the page.

**Comment by verlok** [comment]
Anyway, I'm thinking about the way to do it in the script that manages your page. Would you like me to suggest you how to do it?

**Comment by zedL** [comment]
Hey,

well you currently doing this with the loading class. But you remove this class and add loaded when the images loading is finished.
I only need this behavior the first run and instead of loading use a different class like first-lazy-load.
You currently doing what I need, but you do it again and again on each cycle. I need it only the first time.
Hope that clarify a bit what I mean. If you have a different solution I would be happy to hear about.

**Comment by verlok** [comment]
Thank you, you were absolutely clear. The point is there's no such thing as the "first run". Take a look at the code and you will understand.

**Comment by zedL** [comment]
Hey, 

I could take a look at the code and I have following suggestion.
1. add a variable on top _isFirstLoop = true;
2. in the _loopThroughElements method you can add a class to each identified element
```
if (_isInsideViewport(element, settings.container, settings.threshold)) {
       if (_isFirstLoop) {
          console.log('this element was detected in first loop', element);
          element.classList.add("first-lazy-load");
        }
}
```
3. at the end of the _loopThroughElements method set _isFirstLoop to false
```
if (_isFirstLoop) {
      _isFirstLoop = false;
      console.log('this was the first loop of _loopThroughElements')
// add
    }
```

**Comment by verlok** [comment]
Good idea, you can do it in a fork if you want, but I'm not keen to integrate this change in LazyLoad. 
The reason is that you should *NOT* use Javascript to load the first N images - N depending on the layout of your website in the widest viewport - and to lazily load only from the Nth+1 image on. 
So you should put the first images `src`s and `srcset`s directly in the image tag, then start putting them in the data-* attributes.

An example:

```html
<img alt="..." src="image1.jpg" srcset="image1.jpg 1x, image1@2x.jpg 2x">
<!-- ...and so on until Nth image, then... -->
<img alt="..." class="lazy" data-src="imageN.jpg" data-srcset="imageN.jpg 1x, imageN@2x.jpg 2x">
```

```js
var ll = new LazyLoad({
    elements_selector: "img.lazy",
});
```

**Comment by zedL** [comment]
Well when I have to detect wich images should be displayed based on current viewport I would have two pieces of code that do the same thing in my view. 

If you dont want to improve your lib in this way... it is ok. In my eyes your arguments are strange.

**Comment by verlok** [comment]
You don't have to detect wich images should be displayed based on current viewport, also because you can't do it on the server side. Just set a number fixed to 10 or 12 and write the first HTML for the first 10 or 12 images, then the lazy load HTML for the 13th image on. I can assure it's a best practice. We use it in production in multiple e-commerce websites - in the category page - and it works!

**Comment by zedL** [comment]
This suggestion isnt a good advise.
I display thumbnails in responsive designed views. From little mobile views to large desktop views.
The range of visible images is from 6 on mobile to 60 on desktop.
I want to find a solution for loading and fading in only images that are not on the initialized loaded view.
A fixed count let pop in the first images and the rest fade in, that looks very ugly on larger views. And I would load more data as I need on mobile when I would increase the fixed count to 60 in my case.

"I always pass on good advice. It is the only thing to do with it. It is never of any use to oneself. "
Oscar Wilde

**Comment by verlok** [comment]
Uhm, you're right, there is too much difference between the mobile viewport and the large desktop viewport in your case. Don't do what I said for 60 images. But please do it for the first 6, your mobile users will have a performance boost since the browser will start downloading the images even before downloading the first bit of JavaScript.

**Comment by verlok** [comment]
I'll see what I can do with your suggestion. I'm a little bit busy these days. If you make the change in your girl I might accept a pull request. Thanks

**Comment by zedL** [comment]
ok, you have a new PR

**Comment by verlok** [comment]
@zedL I'm working on this issue. New release coming soon.

**Comment by verlok** [comment]
@zedL done. You can find the edit in the branch `feature/initialViewportClass`. Try it out and tell me if it works for you. If it is, I'll merge it in. Thanks.

**Comment by verlok** [comment]
Hi @zedL, thanks for the delay. I did it!

**Comment by zedL** [comment]
Hello @verlok,
thanks a lot, I will try.

**Comment by verlok** [comment]
@zedL I released another version (6.3.1) with the class name being `initial` like you suggested.

**Comment by verlok** [comment]
There's also a demo in the demos folder. It fades in all the images except the first batch.

**Comment by zedL** [comment]
Thats nice, thanks a lot. I will use it in my project.

**Comment by verlok** [comment]
Glad to hear that ;)

**Comment by verlok** [comment]
Psst: have you already starred this repo? All you need to do is to press the Star ★ button on the top right corner of the website. ;)
