### ISSUE TITLE
Is it possible to re-lazyload an element that is already in the viewport?

### ISSUE THREAD

**Issue by imfelipe** [verlok/lazyload#84]
I have the following situation:
I have a series of images that are lazyloaded. Given an event, I'll update all src attributes with new values, and I want these values to be lazyloaded.
This works fine when the images are *not* in the viewport, but images there are in the viewport are not loaded. Like so:
```html
<!-- These are in the viewport when the event occurs -->
<img class="initial loaded" src="img1.jpeg"/>
<img class="initial loaded" src="img2.jpeg"/>
...
<!-- These are not. It doesn't matter if they were already loaded or not -->
<img class="initial loaded" src="img20.jpeg" />
<img data-original="img21.jpeg"/>
```
When the event happens, I replace the elements:
```html
<!-- src attribute, classes initial and loaded are removed. 
data-original is put back in with new image -->
<img data-original="img30.jpeg"/>
<img data-original="img31.jpeg"/>
...
<!-- Same thing down here -->
<img data-original="img50.jpeg"/>
<img data-original="img51.jpeg"/>
```
Then I call ```lazy.reload()```. It works fine for all img that are *not in the viewport when the event happens*. If the tag is in the viewport, the script doesn't recognize it and I just get a blank space. Scrolling down loads the new images normally.
The workaround is simply remove the element and put another in place:
```javascript
let old_img = document.getElementById(id);
let parent = old_img.parentElement;
parent.removeChild(old_img);
let img = document.createElement('img');
img.setAttribute('data-original',new_src);
parent.append(img);
```
This way lazyload recognizes the new data-original, not mattering if they were or not in the viewport, and the images are loaded appropriately after calling ```.reload```

Is this the proper way to do this? Is there another way?

**Comment by verlok** [comment]
Hi @imfelipe,
thank you for asking here.

What happens is expected, because LazyLoad marks the images that have already been processed and never looks back to them again. I did this to boost performance.

What I suggest you to do is, when you need to update your images, check before if they have a `src` already  set. 

If the `src` attribute was already set, to update the image you should set the `src` attribute directly.
If the `src` attribute is still `null` - meaning the image hasn't been processed yet - you can set the `data-original` attribute as you're currently doing.

This should do the trick.

**Comment by imfelipe** [comment]
hmm this won't help, because if all images in the screen were loaded, when I update the `src=` I would make a bunch of requests, and I wouldn't be lazyloading.
It makes sense optimization wise, though, and what I want to do is kinda awkward. It's all right. Thanks!

**Comment by verlok** [comment]
Ok so in the latest version I'm using `dataset`s to mark the element as processed ([see code here](https://github.com/verlok/lazyload/blob/master/dist/lazyload.transpiled.js)), so you could mark the element as NOT processed after setting the image source in the data-original element.

Long story short, I suggest you to do the following:

```js
function setNewSrc (imgEl, newSrc) {
    imgEl.dataset.original = newSrc;
    imgEl.dataset.wasProcessed = false;
    // optionally, if you want to avoid seeing the old image when the user scrolls back...
    imgEl.setAttribute('src', null);
}

// and when you're finished updating the image source
myLazyLoad.update();
```

What do you think?

**Comment by imfelipe** [comment]
Oh, I think I got it!
Setting `wasProcessed` to false breaks the lazy-loading in all my tests. So we just apply drastic measures and brutally remove it. Solved!
I was making a fiddle to show I wanted to do, and got it working, check this out: https://fiddle.jshell.net/imfelipe/nctzz5gv/1/

```javascript
var img = document.getElementById(id)
img.removeAttribute('src') 
img.classList.remove('loaded') //Not necessary, but no harm.
img.setAttribute('data-original',new_img_src)
img.removeAttribute('data-was-processed') //The catch
//...
lazyload.update()
```

**Comment by verlok** [comment]
Seems good to me. Great!

**Comment by trompx** [comment]
Hello @verlok,

I don't know if this is the same issue, but I built a multiple column infinite scroller. When the user scrolls really fast, sometimes the element is added a bit late to the DOM and I guess it must be added when the lazyload thresold has been already passed. I am not sure though, no data-processed or loaded/dataset attribute is added to the elements, the data-src is still present and no src is set so I assume it is what happens.

I had set the thresold to half screen height, as it is approximatly when the new DOM elements are appended so the image is already visible they enter the viewport. I would like them to start downloading as soon as they are appended if they are within the thresold.
I tried thresold = 0, it is better but I still sometimes have image not loaded, I guess because they are appended when already in the viewport.

As the image has no dataset flag / loaded class, it should still be checked each time I myLazyload.update() (which is called on each scroll) no?

Any hack welcome :)

Thank you for the great package anyway!

**Comment by verlok** [comment]
Hi @trompx,

first of all: Which version of LazyLoad are you using, 10.3.3 or 8.2.1? The recommended version for browser compatibility reasons is 8.2.1, but the most modern one in terms of image detection is 10.3.3 because it uses `IntersectionObserver`.

Second question: do the inserted `img` tags have a `min-height` set? If it did, you would obtain a better performance since less images would be in the viewport when the `src` is not set and loaded.

> As the image has no dataset flag / loaded class, it should still be checked each time I myLazyload.update() (which is called on each scroll) no?

Yes, the `update` method re-selects all the elements with the selector specified in `settings.elements_selector` (the default value is `'img'`), minus the elements that have the `was-processed` data.

Anyway, beware in calling the `update` method on each scroll! It's very CPU consuming. You should call this method only each time you add new images to the DOM.

I hope you find my indications useful.
If you didn't manage to solve this issue, feel free to post some HTML and JS code here or to create a new Pen on [Codepen](http://codepen.io/) and share it here.

**Comment by trompx** [comment]
Hello @verlok,

Thanks a lot for trying to help, I really appreciate.
In fact I use version 8.2.1 because I need mainly mobile compatibility.

I layout my multi columns in js so every element has a height calculated according to the image dimensions stored in db so every new appended image already fully occupies the space.

My bad, when I said I was using `update  `on each scroll, I meant that on each scroll I check if new nodes have to be appended and if there are any, then I trigger an update. So with what you say, images that have not been processed should have their `data-src` converted to `src ` even if they are already in the viewport, so I guess there is something going wrong at one point on my side..

As I have full control of what is appended to the DOM, maybe the `update` function is overkill for me (despite the fact I did not notice any slowdown, probably due to the fact that I limit the number of elements in the DOM so the update have to loop just a few elements), I am thinking about not using lazyloading, in fact in this case, I control the amount of element displayed on screen so loading the X image I append down the screen may be alright.

If I manage to figure it out, I'll let you know as it is an interesting use case.

Cheers!

**Comment by trompx** [comment]
Hello @verlok,

I investigated a bit more as I still had images that were not displaying and managed to slim down the issue. I am using `thresold = 0`.

I found out that when they are not displayed, they don't have the `data-src` parameter anymore but they still don't have the `src` set. To be able to display them, I have to scroll past them then make them enter viewport again, at which point the `src` tag is added.
Besides, manually triggering the update while they are visible on screen without the `data-src` and the `src` doesn't do anything.

I don't know if this is the excpected behaviour. The site is still not online so I cannot provide you a test case but maybe with that you could figure out something.

**Comment by verlok** [comment]
Hi @trompx,
some notes about what you wrote.

* The option name is `threshold`, not `thresold`, make sure you spelled it correctly.
* I can't see why the `data-src` attribute would disappear at some point, since LazyLoad doesn't remove it anywhere (I checked).
* It's correct that calling `update()` it doesn't show the images, it's only useful to check if newer elements matching the same selector (default: `img`) were added to the DOM.

One way that I use to debug my websites is to check if the bug occurs also isolating the code on [Codepen](https://codepen.io). Try that, then maybe post the Pen's URL in a comment, otherwise I can't be of much help if I can't see the code and the bug reproduces.

Ultimately, please consider updating to v8.6.0 after reading the [CHANGELOG](https://github.com/verlok/lazyload/blob/master/CHANGELOG.md). This won't fix your issues, but you'll have a more modern version and some bugs fixed.
